# This is a basic workflow to help you get started with Actions

name: ACPAnalytics CI/CD

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
 
env:
  UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    name: Build ACPAnalytics
    # The type of runner that the job will run on
    runs-on: macOS-latest
    
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2
      with:
        lfs: true
        
    # Cache
    - uses: actions/cache@v1.1.0
      with:
        path: cache
        key: cache
        
    # Test
    - name: 'run unity tests'
      uses: ncipollo/unity-action@master
      with: 
        username: ${{ secrets.username }}
        password: ${{ secrets.password }}
        license: ${{ secrets.license }}

    # Upload artifact
    - uses: actions/upload-artifact@v1
      with:
        name: Test results
        path: bin

    # Build
    - name: Build project
      uses: webbertakken/unity-builder@v0.10
      with:
        unityVersion: 2019.3.11f1
        targetPlatform: iOS

    # Output 
    - uses: actions/upload-artifact@v1
      with:
        name: Build
        path: bin
