name: ACPAnalytics CI/CD

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
 
env:
  UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    name: Build ACPAnalytics
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2
      with:
        lfs: true
        
    # Cache
    - uses: actions/cache@v1.1.0
      with:
        path: cache
        key: cache

    # Build
    - name: Build project
      uses: webbertakken/unity-builder@v0.10
      with:
        unityVersion: 2019.3.11f1
        targetPlatform: iOS

    # Output
    - uses: actions/upload-artifact@v1
      with:
        name: Build
        path: bin
